recipes-kernel/linux/linux-yocto-onl_5.10.bb

Update Linux 5.10 to it's newest release, 5.10.70.
In absence of a 5.10.70 bump yet in meta, bump to HEAD, which has a kver
bump to 5.10.69.

linux-yocto-onl/5.10: update to 5.10.70

---

conf/layer.conf
recipes-bsp/u-boot/u-boot-fw-utils_%.bbappend

Warrior is old, and now untested for quite a while, so let's drop
compatibility with it.

drop warrior support

---

recipes-extended/onl/onl_git.bb

Github just turned off the git transport on their servers, and checking
out now fails with:
fatal: remote error:
The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
So switch to https to make stuff build again.

onl: switch git transport to https for github

---

recipes-kernel/linux/linux-yocto-onl-linux-5.10.y/bisdn-kmeta/bsp/armel-iproc/brcm-iproc-5.10.patch
recipes-kernel/linux/linux-yocto-onl_5.10.bb

Update to 5.10 to the newest release, 5.10.78, and update kernel-meta
accordingly.

linux-yocto-onl/5.10: update to 5.10.78

---

recipes-kernel/linux/linux-yocto-onl-linux-5.10.y/bisdn-kmeta/bsp/armel-iproc/10-02-arm-add-iproc-xgs.patch
recipes-kernel/linux/linux-yocto-onl-linux-5.10.y/bisdn-kmeta/bsp/armel-iproc/10-17-usb-iproc-xgs-hack.patch

Handling of this usb quirk was added to the kernel with https://github.com/torvalds/linux/commit/dfee57a8a6655f3b87fc34c3c07a8b05fd2aae29, so
activate it by adding the appropriate compatible string and drop the
broadcom variant.

armel-iproc: use upstream usb quirk implementation

---

recipes-kernel/linux/linux-yocto-onl_5.15.bb

Update to latest and gratest, with plenty of fixes.

linux-yocto-onl/5.15: update to 5.15.6

---

conf/machine/accton-as4630-54pe.conf
recipes-core/platform-as4630-54pe/files/platform-as4630-54pe-init.sh
recipes-kernel/accton-as4630-poe-mcu/accton-as4630-54pe-poe-mcu-mod_1.0.bb
recipes-kernel/accton-as4630-poe-mcu/files/COPYING
recipes-kernel/accton-as4630-poe-mcu/files/Makefile
recipes-kernel/accton-as4630-poe-mcu/files/accton_as4630_54pe_poe_mcu.c
recipes-kernel/accton-as4630-poe-mcu/files/poectl

Add a driver for the PoE PSE MCU, adapted from the one for AS4610.
Main difference is that this one uses I2C to communicate, and does not need to program the MCU anymore, since it comes with a valid configuration.

accon-as4630-54pe: add PoE support

---

recipes-kernel/linux/linux-yocto-onl_5.15.bb

Update kernel and meta to 5.15.14.
Most interesting/relevant changes come from 5.15.7:
net: mpls: Fix notifications when deleting a device
commit 7d4741eacdefa5f0475431645b56baf00784df1f upstream.
There are various problems related to netlink notifications for mpls route
changes in response to interfaces being deleted:
* delete interface of only nexthop
DELROUTE notification is missing RTA_OIF attribute
* delete interface of non-last nexthop
NEWROUTE notification is missing entirely
* delete interface of last nexthop
DELROUTE notification is missing nexthop
All of these problems stem from the fact that existing routes are modified
in-place before sending a notification. Restructure mpls_ifdown() to avoid
changing the route in the DELROUTE cases and to create a copy in the
NEWROUTE case. …

linux-yocto-onl/5.15: update to 5.15.14

---

recipes-kernel/accton-as4630-poe-mcu/files/poectl

The i2c path for the poe driver for the accton as4630-54pe
is present under /sys/kernel/debug/16-0020.
Signed-off-by: Rubens Figueiredo <rubens.figueiredo@bisdn.de>

accton-as4630-54pe: Fix poectl i2c device path

---

recipes-kernel/linux/linux-yocto-onl_5.15.bb

Update 5.15 to latest, and meta accordingly.
Most interesting fixes from 5.15.19:
net: bridge: vlan: fix memory leak in __allowed_ingress
[ Upstream commit fd20d9738395cf8e27d0a17eba34169699fccdff ]
When using per-vlan state, if vlan snooping and stats are disabled,
untagged or priority-tagged ingress frame will go to check pvid state.
If the port state is forwarding and the pvid state is not
learning/forwarding, untagged or priority-tagged frame will be dropped
but skb memory is not freed.
Should free skb when __allowed_ingress returns false.
net: bridge: vlan: fix single net device option dumping
[ Upstream commit dcb2c5c6ca9b9177f04abaf76e5a983d177c9414 ]
When dumping vlan options for a single net device we send the same
entries infinitely because user-space expects a 0 return at the …

linux-yocto-onl/5.15: update to 5.15.22

---

recipes-extended/onl/onl_git.bb

Newer bitbake versions will complain loudly when no branch is set,
so set it accordingly.

onl: set branch for git repositories

---

recipes-extended/onl/onl_git.bb

Update onl and bigcode to latest HEAD, and update the repo locations accordingly to onl's latest commit.
Brings in mostly as5915-18x support for onl, and 100G-ACC/AOC-LBER module for bigcode.
Infra was not updated to HEAD, as the latest changes break the compilation, but aren't used yet anyway.

onl: udpate to latest HEAD

---

recipes-extended/onl/onl/0001-ym2651y-fix-update-when-MFR_MODEL_OPTION-is-uninmple.patch
recipes-extended/onl/onl_git.bb

Not every PSU implements the MFR_MODEL_OPTION register. If it does not
it will return 0xff on read, which will then subsequently break trying
to read out the full string.
The value of 0xff causes an integer overflow to 0 when trying to read
the whole string, which then causes the I2C driver to reject the 0
length read with -71 (EPROTO):
```
[ 1480.358408] ym2651 50-005b: reg 208, err -71
```
This e.g. breaks AS7726-32X-F with FSF019-611 PSUs, which do not have
this register implemented.
Example error output when running onlpdump(onlps):
```
psu @ 1 = {
05-13 10:25:53.198289 [onlplib] Failed to read input file '/sys/bus/i2c/devices/50-005b/psu_fan_dir'
Description: PSU-1
Model:  FSF019-611
SN:     NULL
Status: 0x00000005 [ PRESENT,UNPLUGGED ]
Caps:   0x00000000
Vin:    0
Vout:   0
Iin: …
```

ym2651y: fix update when MFR_MODEL_OPTION is uninmplemented

---

recipes-kernel/ym2651y-mod/files/ym2651y.c

We also need to patch our local copy, not just ONL.
Fixes: ee55091b7397 ("ym2651y: fix update when MFR_MODEL_OPTION is uninmplemented")

ym2651y: actually apply PSU MFR_MODEL_OPTION fix to module

---

recipes-extended/onl/onl/0001-accton-as4610-do-not-try-to-read-out-PSU-values-for-.patch
recipes-extended/onl/onl_git.bb

Reading PSU output values on YM-1921 seems to be unreliable and can
lockup the I2C bus, which causes system hangs and ultimately resets by
the watchdog. Other PSUs seem to be fine, so it looks like an issue with
the PSU, not the I2C bus.
So for now treat the YM-1921 PSUs as unsupported for these values.
Fixes: de779deb8dc1 ("onl: update to latest HEAD")

accton-as4610: do not try to read out PSU values for YM-1921

---

recipes-kernel/linux/linux-yocto-onl_5.15.bb

Update to include the latest fixes from upstream. Update meta to HEAD,
lacking a v5.15.44 commit yet.
Most interesting change from 5.15.44:
ping: fix address binding wrt vrf
commit e1a7ac6f3ba6e157adcd0ca94d92a401f1943f56 upstream.
When ping_group_range is updated, 'ping' uses the DGRAM ICMP socket,
instead of an IP raw socket. In this case, 'ping' is unable to bind its
socket to a local address owned by a vrflite.
Before the patch:
$ sysctl -w net.ipv4.ping_group_range='0  2147483647'
$ ip link add blue type vrf table 10
$ ip link add foo type dummy
$ ip link set foo master blue
$ ip link set foo up
$ ip addr add 192.168.1.1/24 dev foo
$ ip addr add 2001::1/64 dev foo
$ ip vrf exec blue ping -c1 -I 192.168.1.1 192.168.1.2
ping: bind: Cannot assign requested address
$ ip vrf exec blue …

linux-yocto-onl/5.15: update to 5.15.44

---

recipes-core/platform-as4630-54pe/files/platform-as4630-54pe-init.sh

By default the CPLD has the control over the SFP LEDs. To allow them to
be controlled by the switch ASIC, they need to be set to MAC mode by
enabling bit 7 in the OTHER register of the CPLD.

platform-as4630-54pe: allow SFP LEDs to be controlled by the switch

---

recipes-kernel/linux/linux-yocto-onl-linux-5.15.y/bisdn-kmeta/bsp/armel-iproc/armel-iproc.cfg

Do not disable VXLAN in the config, so that kernel meta snippets can
enable it.
While not supported by Helix 4, this aligns the configs across platforms
a bit.

yocto-linux-onl: armel-iproc: do not disable VXLAN

---

conf/machine/accton-as4610.conf
conf/machine/accton-as4630-54pe.conf
conf/machine/accton-as5835-54x.conf
conf/machine/accton-as7726-32x.conf
conf/machine/agema-ag5648.conf
conf/machine/agema-ag7648.conf
conf/machine/cel-questone-2a.conf

Combining overrides with += is not officially supported, and will
trigger a warning in newer yocto releases [1]:
WARNING: MACHINE_FEATURES:remove += is not a recommended operator combination, please replace it.
[1] https://docs.yoctoproject.org/dev/migration-guides/migration-4.0.html#append-prepend-in-combination-with-other-operators

conf: fixup override usage

---

recipes-extended/onl/onl.inc
recipes-extended/onl/onl_git.bb

Rework the onl package into a generic package:
1. build and ship all libonlp-<platform>.so for all supported machines
2. drop the /etc/onl/platform symlink, and let the installer take care of it
3. replace the libonlp-platform.so symlink with the dummy libonlp-platform.so library from onl
Building all platforms at once means we also get build checks for all platforms when building an image, and not just the selected platform. This is also needed for as4610 so we can properly setup the libonlp symlink based on the running machine.
Having a proper libonlp-platform.so instead of a symlink makes it easier for other packages to link against it, as it won't be an alias for the current machine's libonlp-* anymore, which might have additional dependencies. 
The installer will take care of …

onl: support all platforms

---

recipes-core/platform-as4610/files/platform-as4610-init.sh

Now that the installer will populate /etc/onl/platform, there is no need
to set it during boot anymore.
Depends on https://github.com/bisdn/bisdn-onie-additions/pull/8

platform-as4610: do not setup /etc/onl/platform anymore

---

recipes-kernel/linux/linux-yocto-onl-linux-5.15.y/bisdn-kmeta/cfg/0001-tun-allow-setting-hwaddr-on-tap-interface-creation.patch
recipes-kernel/linux/linux-yocto-onl-linux-5.15.y/bisdn-kmeta/cfg/bisdn-linux.scc

To allow baseboxd to create tap interfaces with the OpenFlow provided
MAC address, we need to allow creating tap interfaces with a fixed MAC
address, so allow passing a MAC address via the ifr_addr field.

linux-yocto-onl: allow setting mac address on tap interface creation

---

recipes-kernel/linux/linux-yocto-onl_5.15.bb

Our kernel is falling behind, so update to latest and gratest.
Kernel-meta updated to HEAD, lacking a v5.15.56 commit.
To allow easier bisection in case of issues, split up the kernel updates along the kver bumps in kernel-meta.
Boot tested on AS4610 and AG7648.

linux-yocto-onl: update to 5.15.56

---

recipes-core/platform-questone-2a/files/platform-questone-2a-init.sh

Make sure the switchboard_cpld module is loaded, else onlpdump will
throw errors.
the switchboard_cpld was autoloaded when it was built seperately, but
yocto did not provide this anymore when we moved the module build into
ONL.
Fix this by loading the moedule explicitly when initializing the
platform, like we do for all other platforms.
Fixed the following errors shown by onlpdump:
sh: line 1: /sys/devices/platform/sys_cpld/getreg: No such file or directory
cat: can't open '/sys/devices/platform/sys_cpld/getreg': No such file or directory
PSU 1
Description: PSU-Left
State: Missing
PSU 2
Description: PSU-Right
State: Missing
LED 1
sh: line 1: /sys/devices/platform/sys_cpld/getreg: No such file or directory
cat: can't open '/sys/devices/platform/sys_cpld/getreg': No such file or directory …

platform-questone-2a: load switchboard cpld module

---

recipes-core/platform-as4610/platform-as4610_0.1.bb
recipes-core/platform-as4630-54pe/platform-as4630-54pe_0.1.bb

The 90-enp.link isn't part of user configuration, and should therefore
be in /lib/systemd/network instead of /etc/systemd/network, so move it
there.
Only Accton AS4610 and Accton AS4630-54PE ship a 90-enp.link, other platforms are not affected.

move management port config from /etc/systemd/network to /lib/systemd/network

---

recipes-extended/onl/onl_git.bb

for some unknown reason th x86-64-delta-ag7648-i2c-mux-setting module
causes a deadlock when loaded too late, so force it being loaded
earlier by loading it explicitly.

onl: delta-ag7648: work around deadlock in module load

---

recipes-core/platform-as4630-54pe/files/platform-as4630-54pe-init.sh

When the optoe module is loaded on demand, the first optoe device
creation may be slow enough that the port_name file does not exist yet
when we try to set it.
Fix this by wating for it to exist before we try to write to it.
Fixes the following error on boot:
```
Aug 25 08:42:19 accton-as4630-54pe systemd[1]: Starting Setup platform as4630-54pe...
Aug 25 08:42:20 accton-as4630-54pe platform-as4630-54pe-init.sh[2013]: /usr/bin/platform-as4630-54pe-init.sh: line 11: /sys/bus/i2c/devices/18-0050/port_name: Permission denied
Aug 25 08:42:20 accton-as4630-54pe systemd[1]: platform-as4630-54pe-init.service: Main process exited, code=exited, status=1/FAILURE
Aug 25 08:42:20 accton-as4630-54pe systemd[1]: platform-as4630-54pe-init.service: Failed with result 'exit-code'.
```
Fixes: 70ef7c292ad3 …

platform-as4630-54pe: make sure optoe device is present

---

conf/machine/accton-as4630-54pe.conf
recipes-core/platform-as4630-54pe/files/platform-as4630-54pe-init.sh
recipes-extended/onl/files/accton-as4630-54te/0001-accton-as4630-54te-silence-unused-result-warning.patch
recipes-extended/onl/files/accton-as4630-54te/0002-Edgecore-as4630_54te-Update-thermal-threshold.patch
recipes-extended/onl/files/accton-as4630-54te/0003-Edgecore-as4630_54te-Support-YM-1151F-power-supply.patch
recipes-extended/onl/onl_git.bb

Add support for Edgecore EPS201 (Accton AS4630-54TE) to the accton-as4630-54pe machine.
The AS4630-54TE and AS4630-54PE are very similar, with the main difference being PoE support and the used PSUs.
So enhance the existing AS4630-54PE image with AS4630-54TE support by enabling the support in ONL, and update the platform init script to load the appropriate modules based on the platform.
Also import to (currently open) PRs from ONL itself to [set proper thermal thresholds](https://github.com/opencomputeproject/OpenNetworkLinux/pull/906), and [support the PSU that is found in our device correctly](https://github.com/opencomputeproject/OpenNetworkLinux/pull/907).
We do not need to [disable iommu](https://github.com/opencomputeproject/OpenNetworkLinux/pull/897) as we already do that. …

accton-as4630-54pe: add support for edgecore eps201(as4630-54te)

---

recipes-extended/onl/files/accton-as4610/0004-accton_as4610_cpld-add-of-device-match-table.patch
recipes-extended/onl/files/accton-as4610/0005-accton_as4610_psu-add-of-device-match-table.patch
recipes-extended/onl/files/accton-as4610/0006-accton-as4610-let-CPLD-handle-the-FAN-device.patch
recipes-extended/onl/files/accton-as4610/0007-accton-as4610-fix-FAN-driver-id-table.patch
recipes-extended/onl/files/accton-as4610/0008-accton-as4610-let-CPLD-handle-the-LED-device.patch
recipes-extended/onl/files/onl/0013-optoe-add-of-device-match-table.patch
recipes-extended/onl/files/onl/0014-ym2561y-add-of-device-match-table.patch
recipes-extended/onl/onl_git.bb

Fix the on-demand loading of modules by providing proper id tables for
all relevant drivers, and let the CPLD driver instantiate the LED and
FAN devices if present instead of the modules themselves in their init
functions.

accton-as4610: fix on-demand loading of modules

---

recipes-extended/onl/onl.inc

ARCH will already be properly populated by Yocto with the correct kernel
ARCH, so do not override with TARGET_ARCH, which only sometimes
correlates with the kernel ARCH.

onl: do not override ARCH

---

recipes-kernel/linux/linux-yocto-onl_5.15.bb

Update the kernel to latest 5.15.64 and kernel meta to HEAD in absence
of a 5.15.64 commit.
Most interesting change is from 5.15.64:
bonding: 802.3ad: fix no transmission of LACPDUs
[ Upstream commit d745b5062ad2b5da90a5e728d7ca884fc07315fd ]
This is caused by the global variable ad_ticks_per_sec being zero as
demonstrated by the reproducer script discussed below. This causes
all timer values in __ad_timer_to_ticks to be zero, resulting
in the periodic timer to never fire.
(reproducer omitted)
Changelogs for the kernel:
* https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.15.64
* https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.15.63
* https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.15.62
* https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.15.61
* …

linux-yocto-onl: update to 5.15.64

---

conf/machine/accton-as4610.conf

Now that we do not try to install grub for arm anymore, we also don't
need to remove it anymore.
Depends on https://github.com/bisdn/meta-switch/pull/113

accton-as4610: no need to remove grub anymore

---

conf/machine/agema-ag5648.conf
recipes-extended/onl/onl.inc
recipes-extended/onl/onl_git.bb

It looks like some (newer?) variants of Delta AG5648V1 report themselves as delta_ag5648v1 instead of the expected delta_ag5648 in [ONIE](https://github.com/opencomputeproject/onie/tree/master/machine/delta) as their machine name. This causes issues as there is no such machine in ONIE, nor in [ONL](https://github.com/opencomputeproject/OpenNetworkLinux/tree/master/packages/platforms/delta/x86-64).
Under the assumption that hardware-wise the AG5648V1 identifying as delta_ag5648 and the one identifying as delta_ag5648v1 are identical, add it to ONL_PLATFORM_SUPPORT and tell ONL to not try to build anything for it.
Depends on https://github.com/bisdn/meta-switch/pull/115 so that the installer supports it.

agema-ag5648: add support for delta_ag5648v1 variant

---

recipes-core/platform-ag7648/files/platform-ag7648-init.sh
recipes-extended/onl/files/delta-ag7648/0011-delta-ag7648-do-not-reset-QSFP-modules-when-IRQ-is-a.patch
recipes-extended/onl/onl_git.bb

Fix two issues with handling of (mainly) optical QSFP modules:
1. Do not assume an asserted IntL signal means that the module has an error, it may also just mean it finished initializing, so do not reset modules in response to an asserted IntL.
2. Do not limit modules to the lowest power class by disabling LP Mode.
Especially 1. caused slow onlpdump output when an optical module is inserted, as every read from any QSFP eeprom triggered a reset loop until the the timeout is reached or so. This also had the side effect of breaking any active link in optical modules.

agema-ag7648: fix support of optical QSFP modules

---

recipes-extended/onl/files/accton-as4630-54te/0004-accton-as4630-54te-do-not-acccess-PSU-via-pmbus.patch
recipes-extended/onl/onl_git.bb

Accessing the PSUs via pmbus seems to have a chance of locking up the I2C bus. After that, any I2C access fail:
```
[ 5740.409947] ismt_smbus 0000:00:12.0: completion wait timed out
[ 5741.433936] ismt_smbus 0000:00:12.0: completion wait timed out
[ 5742.457922] ismt_smbus 0000:00:12.0: completion wait timed out
[ 5743.481914] ismt_smbus 0000:00:12.0: completion wait timed out
[ 5744.569919] ismt_smbus 0000:00:12.0: completion wait timed out
```
Until we have a known fix/workaround, disable the pmbus accesses for now.

accton-as4630-54te: do not acccess PSU via pmbus

---

recipes-kernel/linux/linux-yocto-onl_5.15.bb

Update kernel to 5.15.77 and kmeta to HEAD.
Changelog for kernel:
* https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.15.77

linux-yocto-onl: update to 5.15.77

---

recipes-core/platform-as4610/files/90-enp.link
recipes-core/platform-as4610/platform-as4610_0.1.bb
recipes-core/platform-as4630-54pe/files/90-enp.link
recipes-core/platform-as4630-54pe/platform-as4630-54pe_0.1.bb

Let the installer take care of setting up the management port config instead of shipping a hardcoded version of the `90-enp.link` in the image. This way we can support multiple switches needing different management configs in one image.
Depends on https://github.com/bisdn/meta-switch/pull/125

drop fixed management port configs

---

recipes-kernel/linux/linux-yocto-onl-linux-5.15.y/bisdn-kmeta/cfg/bisdn-linux.scc

Enable VRF support via our bisdn-linux.scc instead of relying on a bbappend in meta-switch.

linux-yocto-onl: enable VRF support here

---

recipes-core/platform-as4610/files/fw_env.config
recipes-core/platform-as4610/platform-as4610_0.1.bb

Since the installer will now create the fw_env.config file, we do not
need to provide one in the image.
Keep the u-boot-default-env provide, since the libubootenv-bin package
providing fw_{print,set}env has it as a dependency.
Depends on https://github.com/bisdn/meta-switch/pull/128

platform-as4610: drop the fw_env.config file

---

recipes-extended/onl/files/delta-ag7648/0012-delta-ag7648-make-sure-i2c-i801-is-loaded-before-cre.patch
recipes-extended/onl/onl_git.bb

The order in which the modules must be loaded is super fragile: i2c-i801 must be loaded before instantiating the devices.
Neither i2c-ismt nor any of the cpld drivers may be loaded before creating the devices, else only a subset of devices may be created, or the module may hang in init.
We cannot request modules to be unloaded or not loaded, but we can at least make sure that i2c-i801 is loaded and ready.

delta-ag7648: make sure i2c-i801 is loaded before creating devices

---

recipes-kernel/accton-as4630-poe-mcu/accton-as4630-54pe-poe-mcu-mod_1.0.bb

There is no need to autoload the poe driver, as it will be loaded on demand when the I2C device is created by the platform init script.
Avoids loading the module on platforms that do not need it, e.g. accton-as4630-54te.
Fixes: 5dfbbf77bc20 ("accton-as4630-54pe-poe-pse: add driver for PoE")

accton-as4630-54pe-poe-mcu: do not autoload on boot

---

recipes-extended/onl/files/delta-ag7648/0012-delta-ag7648-make-sure-i2c-i801-is-loaded-before-cre.patch
recipes-extended/onl/files/delta-ag7648/0013-delta-ag7648-prevent-potential-deadlock-on-probe.patch
recipes-extended/onl/onl_git.bb

When the i2c-ismt and pca954x modules are already loaded, there will be a deadlock due to recursive locking:
```
i2c_for_each_dev()
mutex_lock(&core_lock) <-- first lock
bus_for_each_dev()
delta_switch_scan_peripherals()
delta_switch_instantiate_i2c_device()
i2c_new_scanned_device()
...
i2c_device_probe()
pca954x_probe()
i2c_mux_add_adapter()
i2c_add_adapter()
mutex_lock(&core_lock) <-- deadlock
```
To avoid this, do not try to add any devices while under the core lock, and just collect the matched adapters, and only after returning from the bus scan, do the device registration.
We still need to make sure that at least i2c-i801 is loaded, as
userspace depends on stable i2c bus numbering, which we can only ensure
when i2c-i801 is probed and has a bus assigned, so the pca941x mux won't
be …

onl: delta-ag7648: properly fix deadlock on probe

---

recipes-kernel/linux/linux-yocto-onl_6.1.bb

While testing/preparing the 6.1 kernel, the i2c-ismt module conf was not properly added to the recipe, causing failures due to unexpected bus numbers again.
So add it again.
Fixes: 32cede492ebc ("linux-yocto-onl: add linux 6.1 support")

linux-yocto-onl: add missing module conf for i2c-ismt

---

recipes-kernel/linux/linux-yocto-onl-linux-5.15.y/bisdn-kmeta/bsp/armel-iproc/10-11-bgmac-xgs-iproc-changes.patch

Readd the part clearing the emulated MiBs on open for the management port driver that was accidentally dropped when removing the mdio hacks.
The side effect was that MiBs weren't cleared properly anymore, but likely nobody noticed.
Reported-by: Roger Luethi <roger.luethi@bisdn.de>
Fixes: 351e020ee9c7 ("linux-yocto-onl: armel-iproc: use upstream IPROC MDIO driver")

armel-iproc: fix clearing MiBs on open for management

---

conf/machine/cel-questone-2a.conf

When moving questone-2a to the generic platform-onl-init, the old RDEPENDS was accidentally left in. This package does not exist anymore so remove it.
Fixes the following build error:
```
ERROR: Nothing RPROVIDES 'platform-questone-2a' (but /builds/yocto-projects/switch-image-builder/poky/meta/recipes-core/packagegroups/packagegroup-base.bb RDEPENDS on or otherwise requires it)
Dec 07 18:05:25 NOTE: Runtime target 'platform-questone-2a' is unbuildable, removing...
Dec 07 18:05:25 Missing or unbuildable dependency chain was: ['platform-questone-2a']
Dec 07 18:05:25 NOTE: Runtime target 'packagegroup-base-extended' is unbuildable, removing...
Dec 07 18:05:25 Missing or unbuildable dependency chain was: ['packagegroup-base-extended', 'platform-questone-2a']
ERROR: Required build target …
```

cel-questone-2a: drop old platform questone-2a rdepends

---

recipes-core/platform-onl-init/files/platform-x86-64-accton-as4630-54pe-r0-init.sh
recipes-core/platform-onl-init/files/platform-x86-64-accton-as5835-54x-r0-init.sh
recipes-core/platform-onl-init/files/platform-x86-64-accton-as7726-32x-r0-init.sh
recipes-core/platform-onl-init/files/platform-x86-64-cel-questone-2a-r0-init.sh
recipes-core/platform-onl-init/files/platform-x86-64-delta-ag5648-r0-init.sh
recipes-core/platform-onl-init/files/platform-x86-64-delta-ag7648-r0-init.sh
recipes-kernel/linux/linux-yocto-onl_5.15.bb
recipes-kernel/linux/linux-yocto-onl_6.1.bb

Using the pre: softdep for forcing a load order of i2c-ismt and i2c-i801 still leaves a window where the i2c-i801 driver has loaded, but not attached, and consequently i2c-ismt may still occationally win the race for the first i2c bus.
Since there is no way to specify any sleeps or waits in the modprobe configuration, blacklist the module and let platforms ensure that the i2c busses are registeredd in the right order in a deterministic way.
Fixes: e024e2ad3dd7 ("linux-yocto-onl: build i2c_i801 as a module and fix probe order")

platform-onl-init: manually load i2c-ismt

---

recipes-kernel/linux/linux-yocto-onl_5.15.bb

Update kernel 5.15 to 5.15.90 and kmeta to HEAD in absence of a 5.15.90 commit.
The usual set of bug fixes for various subsystems.
Changelogs:
* https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.15.90
* https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.15.89
* https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.15.88
* https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.15.87
* https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.15.86
* https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.15.85
* https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.15.84
* https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.15.83
* https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.15.82
* https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.15.81
* …

linux-yocto-onl/5.15: update to 5.15.90

---

recipes-kernel/linux/linux-yocto-onl_6.1.bb

Update the kernel to latest 6.1.8 and kernel meta to HEAD in absence
of a 6.1.8 commit. Also switch kernel-meta to now existing yocto-6.1 branch.
Changelogs:
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.8
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.7
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.6
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.5
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.4
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.3
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.2
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.1

linux-yocto-onl/6.1: update to 6.1.8

---

recipes-core/platform-onl-init/files/platform-arm-accton-as4610-30-r0-init.sh
recipes-core/platform-onl-init/files/platform-arm-accton-as4610-54-r0-init.sh
recipes-core/platform-onl-init/files/platform-onl-init.sh
recipes-core/platform-onl-init/files/platform-x86-64-accton-as4630-54pe-r0-init.sh
recipes-core/platform-onl-init/files/platform-x86-64-accton-as4630-54te-r0-init.sh
recipes-core/platform-onl-init/files/platform-x86-64-accton-as5835-54x-r0-init.sh
recipes-core/platform-onl-init/files/platform-x86-64-accton-as7726-32x-r0-init.sh
recipes-core/platform-onl-init/files/platform-x86-64-cel-questone-2a-r0-init.sh
recipes-core/platform-onl-init/files/platform-x86-64-delta-ag5648-r0-init.sh
recipes-core/platform-onl-init/files/platform-x86-64-delta-ag7648-r0-init.sh
recipes-core/platform-onl-init/platform-onl-init_0.1.bb

Since the different platform init code was initially written as distinct scripts, there is a lot of code duplication between them. So clean that up, unify the code style, and then improve the available functions.
Does the following things:
1. unify code style
2. use common wait_for_file(), create_i2c_dev(), add_port() functions
3. use unique as4610-30/54 and as4630-54pe/te init scripts
4. fix as7726-32x sfp+ port optoe driver type

platform-onl-init: cleanup and refactor code

---

recipes-kernel/linux/linux-yocto-onl_6.1.bb

Update the kernel to latest 6.1.13 and kernel meta to HEAD in absence of a 6.1.14 commit.
Changelogs:
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.14
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.13
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.12
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.11
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.10
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.9

linux-yocto-onl/6.1: update to 6.1.14

---

conf/machine/generic-armel-iproc.conf
conf/machine/generic-x86-64.conf
recipes-bsp/formfactor/formfactor/generic-armel-iproc/machconfig
recipes-bsp/formfactor/formfactor/generic-x86-64/machconfig

Now that everything is in place to support multiple machines at the same time, add generic onl machines that have support for all verified platforms enabled, called onl-\<arch\>.

RFC: add generic onl machines

---

conf/machine/generic-armel-iproc.conf
conf/machine/generic-x86-64.conf

When renaming the generic machines from onl- to generic- renaming the KMACHINE definitions was missed, breaking the build.
Fix this by updating them accordingly.

conf/machine: fix generic machine KMACHINE definition

---

recipes-kernel/accton-as4610-poe-mcu/accton-as4610-poe-mcu-mod_1.0.bb
recipes-kernel/accton-as4610-poe-mcu/files/accton_as4610_poe_mcu.c

There is no need to force load the module, the kernel is capable of requesting it when it encounters a device handled by it. To do that, the module needs to expose the handled device names via `MODULE_DEVICE_TABLE()`. So add one and drop the forced load on boot.

accton-as4610-poe-mcu: only load module on demand

---

conf/machine/accton-as4610.conf
conf/machine/accton-as4630-54pe.conf
conf/machine/accton-as5835-54x.conf
conf/machine/accton-as7726-32x.conf
conf/machine/agema-ag5648.conf
conf/machine/agema-ag7648.conf
conf/machine/cel-questone-2a.conf

Use of BISDN_ONIE_MACHINE has ended with [1].
Use of PLATFORM_VENDOR has ended with [2].
[1] mk_bisdn_yocto_image.sh: drop machine= from machine.conf
https://github.com/bisdn/bisdn-onie-additions/commit/2efb8c8ea3eb16afaa2ffc7101b1c33c232c6d07
[2] installer: flatten machines and use ONIE names
https://github.com/bisdn/meta-switch/commit/322da89169544e0fcd401d1112587420163c3e64

conf/machine: remove unused variables

---

recipes-kernel/linux/linux-yocto-onl_6.1.bb

Update the kernel to latest 6.1.31 and kernel meta accordingly.
Changelogs:
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.31
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.30
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.29
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.28
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.27
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.26

linux-yocto-onl/6.1: update to 6.1.31

---

recipes-kernel/linux/linux-yocto-onl_5.15.bb

Update kernel 5.15 to 5.15.114 and kmeta accordingly.
Changelogs:
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-5.15.114
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-5.15.113
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-5.15.112
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-5.15.111
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-5.15.110
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-5.15.109

linux-yocto-onl/5.15: update to 5.15.114

---

recipes-kernel/linux/linux-yocto-onl_6.1.bb

Update the kernel to latest 6.1.44 and kernel meta accordingly.
Changelogs:
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.44
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.43
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.42
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.41
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.40
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.39

linux-yocto-onl/6.1: update to 6.1.44

---

recipes-kernel/linux/linux-yocto-onl_6.1.bb

Update the kernel to latest 6.1.46 and kernel meta to 6.1.45, as there is no .46 bump yet.
Most interesting change are:
4.1.45:
* vxlan: Fix nexthop hash size
(fixes a crash with multiple nexthops)
4.1.46:
* nexthop: Fix infinite nexthop bucket dump when using maximum nexthop ID
* nexthop: Fix infinite nexthop dump when using maximum nexthop ID
* bonding: Fix incorrect deletion of ETH_P_8021AD protocol vid from slaves
Full changelogs:
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.45
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.46

linux-yocto-onl/6.1: update to 6.1.46

---

recipes-kernel/linux/linux-yocto-onl_6.1.bb

Update the kernel to 6.1.47. Update kmeta to HEAD in absence of a kver bump.
Most interesting changes are:
* sock: Fix misuse of sk_under_memory_pressure()
* team: Fix incorrect deletion of ETH_P_8021AD protocol vid from slaves
* i2c: bcm-iproc: Fix bcm_iproc_i2c_isr deadlock issue
Full changelog:
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.47

linux-yocto-onl/6.1: update to 6.1.47

---

recipes-kernel/linux/cve-exclusion_5.15.inc
recipes-kernel/linux/cve-exclusion_6.1.inc
recipes-kernel/linux/linux-yocto-onl_5.15.bb
recipes-kernel/linux/linux-yocto-onl_6.1.bb

Add and include generated lists of known fixed CVEs so cve_check won't
warn about them.
Mitre is not particularly good at keeping the list of affected and fixed linux verions up to date. The linux kernel CVEs project [1] tries to take care of that. Therefore add a list of fixed CVEs for each kernel, so the list of CVEs being warned about become more meaningful.
For obvious reasons the list needs to be re-generated on every kernel update.
Generated with generate-cve-exclusions.py from poky [2]
[1] https://github.com/nluedtke/linux_kernel_cves
[2] https://git.yoctoproject.org/poky/tree/meta/recipes-kernel/linux/generate-cve-exclusions.py?h=kirkstone&id=f17c07ff4b979e45e967fab6e0ba9faf83290115

inux-yocto-onl: add generated CVE exclusion lists

---

conf/machine/generic-x86-64.conf
conf/machine/include/onl.inc
recipes-extended/onl/onl.inc
recipes-extended/onl/onl_git.bb

Since we now do not have single-device machines anymore, there is no reason to support dynamically limited ONL builds. So let's reduce complexity and always build all supported platforms.
This also let us drop the need for ignoring unknown platforms, as we
now do not use the ONL_PLATFORM_SUPPORT contents anymore. And since the list is ONL-recipe local, there is no need anymore to have it in ONIE format, and change it to ONL format directly.

onl: always build all platforms

---

recipes-extended/onl/files/onl/0001-file_uds-silence-unused-result-warnings.patch
recipes-extended/onl/files/onl/0002-platform_manager-do-not-ignore-write-return-value.patch
recipes-extended/onl/files/onl/0003-file-check-unix-socket-path-is-short-enough.patch
recipes-extended/onl/files/onl/0004-ym2651y-fix-update-when-MFR_MODEL_OPTION-is-uninmple.patch
recipes-extended/onl/files/onl/0005-WIP-tools-convert-to-python3.patch
recipes-extended/onl/files/onl/0006-dynamically-determine-location-of-python3.patch
recipes-extended/onl/files/onl/0007-onlpm-hardcode-supported-arches.patch
recipes-extended/onl/files/onl/0008-onlpm-add-an-argument-for-just-printing-the-builddir.patch
recipes-extended/onl/files/onl/0009-onlpm-allow-overriding-the-dist-codename-from-enviro.patch
recipes-extended/onl/files/onl/0010-tools-replace-yaml.load-with-yaml.full_load.patch
recipes-extended/onl/files/onl/0011-optoe-allow-compilation-with-linux-5.5-and-newer.patch
recipes-extended/onl/files/onl/0012-kmodbuild.sh-don-t-treat-undefined-symbols-as-errors.patch
recipes-extended/onl/files/onl/0013-optoe-add-of-device-match-table.patch
recipes-extended/onl/files/onl/0014-ym2561y-add-of-device-match-table.patch
recipes-extended/onl/files/onl/0015-modules-do-not-call-hwmon_device_register_with_info-.patch
recipes-extended/onl/files/onl/0016-modules-update-i2c_driver-with-6.1-compatibility.patch
recipes-extended/onl/files/onl/0017-optoe-fix-race-in-sysfs-registraton-on-probe.patch
recipes-extended/onl/onl_git.bb

The optoe driver first creates the sysfs entries and then calls i2c_set_clientdata(), but a very fast userspace may already try to access the sysfs entries before the clientdata was set. This then leads to a NULL pointer access, crashing the kernel.
Fix this by ensuring the sysfs entries are only registered after clientdata is populated.
Fixes the following crash observed on boot:
> Sep 28 18:59:33 accton-as4630-54pe kernel: i2c i2c-18: new_device: Instantiated device optoe2 at 0x50
> Sep 28 18:59:33 accton-as4630-54pe kernel: BUG: kernel NULL pointer dereference, address: 0000000000000048
> Sep 28 18:59:33 accton-as4630-54pe kernel: optoe 18-0050: 33152 byte optoe2 EEPROM, read/write
> Sep 28 18:59:33 accton-as4630-54pe kernel: #PF: supervisor write access in kernel mode
> Sep 28 …

onl: optoe: fix race in sysfs registration on probe

---

recipes-kernel/linux/cve-exclusion_6.1.inc
recipes-kernel/linux/linux-yocto-onl_6.1.bb

Update kernel 6.1 to 6.1.60 and kernel-meta accordingly.
Changelogs:
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.60
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.59
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.58

linux-yocto-onl/6.1: update to 6.1.60

---

conf/machine/generic-armel-iproc.conf
conf/machine/generic-x86-64.conf
recipes-extended/onl/onl.inc
recipes-extended/onl/packagegroup-onl-platform-arm.bb
recipes-extended/onl/packagegroup-onl-platform-x86-64.bb

To better compartmentalize the ONL platform support parts, add packagegroups for each supported platform, and split out the platform libraries from the main onl package.
This will allow adding more platforms to build, but not include in the image to make it easier to lay groundwork for adding new platform support in the future.

onl: add packagegroups and split out platform libraries into own packages

---

recipes-extended/onl/packagegroup-onl-platform-arm.bb
recipes-extended/onl/packagegroup-onl-platform-x86-64.bb

All referenced packages are arch-specific, so it does not make sense for the packagegroups themselves to be generic.

packagegroup-onl-platform-*: set arch

---

recipes-kernel/linux/cve-exclusion_6.1.inc
recipes-kernel/linux/linux-yocto-onl_6.1.bb

We haven't update the kernel in a while so let's update it to 6.1.75 and
kernel-meta to HEAD.
Changelogs:
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.75
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.74
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.73
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.72
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.71
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.70
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.69
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.68
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.67
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.66
* …

linux-yocto-onl/6.1: update to 6.1.75

---

recipes-kernel/generic-armel-iproc-dtbs/files/arm-accton-as4610-54.dts
recipes-kernel/generic-armel-iproc-dtbs/files/arm-accton-as4610.dtsi

The appropriate generic property for setting the mux to disconnect on idle according to [1] is
idle-state = <MUX_IDLE_DISCONNECT>;
"deselect-on-exit" was a custom ONIE/ONL[2] property that was never upstream, so it never did anything for our kernels. ONL kernels also only ever supported it up to 3.16, so even ONL was missing it.
[1] https://elixir.bootlin.com/linux/v6.7.6/source/Documentation/devicetree/bindings/mux/mux-controller.yaml#L85
[2] https://github.com/opencomputeproject/onie/blob/master/patches/kernel/3.2.69/driver-pca954x-i2c-mux-deselect-on-exit-dtb-property.patch

accton-as4610: fix disconnect-on-idle for i2 mux

---

recipes-kernel/linux/cve-exclusion_6.1.inc
recipes-kernel/linux/linux-yocto-onl-linux-6.1.y/bisdn-kmeta/bsp/x86_64-intel/x86_64-intel.cfg
recipes-kernel/linux/linux-yocto-onl_6.1.bb

Update linux 6.1 to 6.1.88 and update kernel-meta to HEAD, in absence of a v6.1.88 commit.
Also drop two kernel config symbols that were removed in 6.1.80:
* NET_SCH_DSMARK with a41f6e170b85 ("net/sched: Retire dsmark qdisc")
* NET_SCH_CBQ with 02149c7cd115 ("net/sched: Retire CBQ qdisc")
Changelogs:
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.88
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.87
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.86
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.85
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.84
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.83
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.82
* …

linux-yocto-onl/6.1: update to 6.1.88

---

recipes-kernel/linux/cve-exclusion_6.6.inc
recipes-kernel/linux/linux-yocto-onl-linux-6.6.y/bisdn-kmeta/bsp/x86_64-intel/igb-setup-Broadcom-54616-PHY-when-no-EEPROM-present.patch
recipes-kernel/linux/linux-yocto-onl_6.6.bb

Update Linux 6.6 to 6.6.29 and kernel-meta to HEAD, in absence of a v6.6.29 commit.
Rebase igb-setup-Broadcom-54616-PHY-when-no-EEPROM-present.patch on changes upstream [1], which also reordered the includes.
Changelogs:
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.29
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.28
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.27
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.26
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.25
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.24
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.23
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.22
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.21
* …

linux-yocto-onl/6.6: update to 6.6.29

---

recipes-kernel/linux/cve-exclusion_6.1.inc
recipes-kernel/linux/linux-yocto-onl_6.1.bb

Update linux 6.1 and kernel-meta to 6.1.90.
Most noteworthy change from 6.1.90:
vxlan: drop packets from invalid src-address
[ Upstream commit f58f45c1e5b92975e91754f5407250085a6ae7cf ]
The VXLAN driver currently does not check if the inner layer2
source-address is valid.
In case source-address snooping/learning is enabled, a entry in the FDB
for the invalid address is created with the layer3 address of the tunnel
endpoint.
If the frame happens to have a non-unicast address set, all this
non-unicast traffic is subsequently not flooded to the tunnel network
but sent to the learnt host in the FDB. To make matters worse, this FDB
entry does not expire.
Apply the same filtering for packets as it is done for bridges. This not
only drops these invalid packets but avoids them from being learnt …

linux-yocto-onl/6.1: update to 6.1.90

---

recipes-kernel/linux/cve-exclusion_6.6.inc
recipes-kernel/linux/linux-yocto-onl_6.6.bb

Update linux 6.6 and kernel-meta to 6.6.30.
Most noteworthy change from 6.6.30:
vxlan: drop packets from invalid src-address
[ Upstream commit f58f45c1e5b92975e91754f5407250085a6ae7cf ]
The VXLAN driver currently does not check if the inner layer2
source-address is valid.
In case source-address snooping/learning is enabled, a entry in the FDB
for the invalid address is created with the layer3 address of the tunnel
endpoint.
If the frame happens to have a non-unicast address set, all this
non-unicast traffic is subsequently not flooded to the tunnel network
but sent to the learnt host in the FDB. To make matters worse, this FDB
entry does not expire.
Apply the same filtering for packets as it is done for bridges. This not
only drops these invalid packets but avoids them from being learnt …

linux-yocto-onl/6.6: update to 6.6.30

---

recipes-kernel/linux/cve-exclusion_6.6.inc
recipes-kernel/linux/linux-yocto-onl_6.6.bb

Update linux 6.6 and kernel-meta to 6.6.35.
Since the upstream repo for the CVE changes got archived, it does not make sense to keep updating the exclusion file, therefore just remove the version check.
Changelogs:
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.35
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.34
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.33
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.32
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.31

linux-yocto-onl/6.6: update to 6.6.35

---

recipes-core/platform-onl-init/files/platform-onl-init.service
recipes-core/platform-onl-init/files/platform-onl-init.sh
recipes-core/platform-onl-init/platform-onl-init_0.1.bb

FHS says [1]:
/usr/libexec includes internal binaries that are not intended to be
executed directly by users or shell scripts. Applications may use a
single subdirectory under /usr/libexec.
which sounds exactly what these scripts are, so move them there.
[1] https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s07.html

platform-onl-init: move scripts to /usr/libexec/

---

conf/machine/generic-armel-iproc.conf

GO on ARM links against the wrong linuxloader, so manually override it until the issue is fixed upstream.
[1] https://patchwork.yoctoproject.org/project/oe-core/patch/20240626141453.84243-1-jonas.gorski@bisdn.de/

generic-armel-iproc: override GO linuxloader

---

conf/machine/generic-armel-iproc.conf

Now that upstream has backported the fix for kirkstone [1], we can drop our local workaround for the issue.
This reverts commit 622ae9b19c47a47f18b8f90ea2ee3321476cceea.
[1] https://github.com/openembedded/openembedded-core/commit/c7426629245db2ea8d9f3cf25b575ac31b5a83b0

generic-armel-iproc: remove local workaround for GO linuxloader

---

recipes-kernel/linux/linux-yocto-onl_6.6.bb

Update linux 6.6 to latest 6.6.44, and kernel-meta to latest HEAD.
Brings the usual set of fixes, including some VRF and source address selection fixes in 6.6.44:
ipv6: take care of scope when choosing the src addr
commit abb9a68d2c64dd9b128ae1f2e635e4d805e7ce64 upstream.
When the source address is selected, the scope must be checked. For
example, if a loopback address is assigned to the vrf device, it must not
be chosen for packets sent outside.
and
ipv4: fix source address selection with route leak
commit 6807352353561187a718e87204458999dbcbba1b upstream.
By default, an address assigned to the output interface is selected when
the source address is not specified. This is problematic when a route,
configured in a vrf, uses an interface from another vrf (aka route leak).
The original vrf …

linux-yocto-onl/6.6: update to 6.6.44

---

recipes-kernel/linux/linux-yocto-onl_6.6.bb

Update linux 6.6 to latest 6.6.45, and kernel-meta to HEAD.
Changelog:
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.45

linux-yocto-onl/6.6: update to 6.6.45

---

recipes-kernel/linux/linux-yocto-onl-linux-6.6.y/bisdn-kmeta/cfg/0001-net-bridge-br_fdb_external_learn_add-always-set-EXT_.patch
recipes-kernel/linux/linux-yocto-onl-linux-6.6.y/bisdn-kmeta/cfg/bisdn-linux.scc

Fix re-setting EXT_LEARN for once EXT_LEARN entries.
This fixes a behavior where kernel clears the EXT_LEARN bit on entries relearned on a different port, but does not allow setting it again for userspace.
Fixes baseboxd failing to update fdb entries when macs move between ports.

linux-yocto-onl: fix resetting EXT_LEARN for updated fdb entries

---

recipes-kernel/linux/linux-yocto-onl_6.6.bb

Update kernel 6.6 to latest 6.6.57 and kmeta to HEAD.
Changelogs:
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.57
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.56
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.55
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.54
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.53
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.52

linux-yocto-onl: update 6.6 to 6.6.57

---

recipes-kernel/linux/linux-yocto-onl_6.6.bb

Update linux 6.6 to latest 6.6.66 and kernel-meta to HEAD.
Changelogs:
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.66
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.65
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.64
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.63
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.62
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.61
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.60
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.59
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.58

linux-yocto-onl/6.6: update to 6.6.66

---

recipes-kernel/linux/linux-yocto-onl_6.6.bb

Update kernel 6.6 to 6.6.71 and kmeta to HEAD.
Changelogs:
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.71
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.70
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.69
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.68
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.67

linux-yocto-onl/6.6: update to 6.6.71

---

recipes-kernel/linux/linux-yocto-onl_5.15.bb

Update linux 5.15 to 5.15.176 and kmeta to latest HEAD.
Changelogs:
* https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.15.176
* https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.15.175

linux-yocto-onl/5.15: update to 5.15.176

---

recipes-kernel/linux/linux-yocto-onl-linux-6.6.y/bisdn-kmeta/cfg/0001-net-bridge-ensure-that-link-local-traffic-cannot-unl.patch
recipes-kernel/linux/linux-yocto-onl-linux-6.6.y/bisdn-kmeta/cfg/bisdn-linux.scc

Make sure link-local like EAPOL frames cannot unlock a locked port by disabling learning from link-local traffic on locked ports.

linux-yocto-onl/6.6: ensure link-local traffic cannot unlock a locked port

---

recipes-kernel/bcm591xx-poe-mcu/files/accton_as4610_poe_mcu.c
recipes-kernel/bcm591xx-poe-mcu/files/accton_as4630_54pe_poe_mcu.c
recipes-kernel/bcm591xx-poe-mcu/files/bcm591xx.c

Fix an inverted condition in the new bcm591xx library code code recently introduced preventing the code from working, and drop various unused variables and includes.

PoE module fixes

---

recipes-kernel/linux/linux-yocto-onl_6.6.bb

Update linux 6.6 to 6.6.83 and kmeta accordingy.
Changelogs:
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.83
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.82
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.81
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.80
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.79
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.78
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.77
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.76
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.75
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.74
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.73
* …

linux-yocto-onl/6.6: update to 6.6.83

---

recipes-kernel/bcm591xx-poe-mcu/files/bcm591xx.c

When moving the port initialiation to the generic library, the disabling of ports was accidentally dropped. This caused all ports to be enabled despite status saying they are enabled.
Fix this by restoring the code disabling the ports by default on startup.
Fixes: 06eeb488b92b ("bcm591xx-poe-mcu: let the generic code take care of initializing ports")

bcm591xx-poe-mcu: disable ports by default again

---

recipes-kernel/linux/linux-yocto-onl_6.6.bb

Update kernel 6.6 to 6.6.100 and kmeta accordingly.
Changelog:
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.100
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.99
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.98
* https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.97

linux-yocto-onl/6.6: update to 6.6.100
